stages:
  - build

variables:
  BLOSSOM_REPO_URL: "https://repo.blossomos.org/rpm/"
  COSIGN_PASSWORD: ""
  GITHUB_TOKEN: ""

.build_base:
  stage: build
  tags:
    - bigboi
  before_script:
    - echo "$COSIGN_PRIVATE_KEY" > cosign.key
    - echo "$CI_REGISTRY_PASSWORD" | podman login registry.blossomos.org -u "$CI_REGISTRY_USER" --password-stdin

# latest (main branch + schedule + manual)

build-generic-latest:
  extends: .build_base
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH != "prerelease" && $CI_COMMIT_BRANCH != "release" && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
  script:
    - sudo ./build.sh latest generic

build-nvidia-latest:
  extends: .build_base
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH != "prerelease" && $CI_COMMIT_BRANCH != "release" && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
  script:
    - sudo ./build.sh latest nvidia

# prerelease

build-generic-prerelease:
  extends: .build_base
  rules:
    - if: '$CI_COMMIT_BRANCH == "prerelease" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
  script:
    - sudo ./build.sh prerelease generic

build-nvidia-prerelease:
  extends: .build_base
  rules:
    - if: '$CI_COMMIT_BRANCH == "prerelease" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
  script:
    - sudo ./build.sh prerelease nvidia

# release

build-generic-release:
  extends: .build_base
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
  script:
    - sudo ./build.sh main generic

build-nvidia-release:
  extends: .build_base
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api")'
  script:
    - sudo ./build.sh main nvidia
